# Generated by Django 3.0.4 on 2020-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0003_group_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('video', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Howtoplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='prize',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
