# Generated by Django 3.0.7 on 2020-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0003_auto_20200629_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default='some-random-content'),
            preserve_default=False,
        ),
    ]
