# Generated by Django 3.0.4 on 2020-06-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise', '0004_auto_20200628_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descrption',
            new_name='description',
        ),
    ]
